### PR TITLE
Paste Java as Ceylon

### PR DESCRIPTION
**Pull request by rohitmohan96**
Added code conversion functionality to the Ceylon IDE.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Lots of unnecessary whitespace changes in the diff… we usually indent with four spaces, not tabs.

**Comment by lucaswerkmeister** [comment]
At a glance, it looks like the changes in `FormatAction.java`, `SourceMenuItems.java`, `CleanImportsHandler.java` are only reformatting (changed indentation, line wrapping, rearranged imports), no actual changes. Is that correct?

**Comment by gavinking** [comment]
Yay! :-)

**Comment by lucaswerkmeister** [comment]
Great! :)

**Comment by gavinking** [comment]
Congratulations, @rohitmohan96! I will try it out today!

P.S. we need to get your repo migrated to the Ceylon organization, since the IDE build now depends on it.

**Pull request merged**
