### PR TITLE
Update Maven version range to include 3.3.9

### PR DESCRIPTION
**Pull request by azolotko**

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
@davidfestal any reason not to merge this? I currently have the exact same patch uncommitted in my working dir because I can’t build without it.

**Comment by davidfestal** [comment]
@lucaswerkmeister : probably because I didn't have the time to test it :-)

**Comment by lucaswerkmeister** [comment]
Well it’s worked for me for a few weeks now :)

**Comment by davidfestal** [comment]
let me merge it then :-)

**Comment by lucaswerkmeister** [comment]
Great, thanks!

**Pull request merged**
