### PR TITLE
Use Escaping and FindDeclarationNodeVisitor from ceylon-ide-common

### PR DESCRIPTION
**Pull request by mmazi**
This moves some dependencies to ceylon-ide-common.

NOTE: ceylon-ide-eclipse must first be made to depend on ceylon-ide-common before merging this.

### CODE REVIEW

**Comment by gavinking** [comment]
@mmazi I guess we never noticed this one come in at the time ... June last year?!

I'm not sure if it's still possible to merge it. It's just @ 8f44ef7475dfbdbe4300a87b9899f22cc764430e, is that right?

Apologies for dropping the ball on this one!

**Comment by mmazi** [comment]
Just 8f44ef7, yes. It simply moves references to Escaping and FindDeclarationNodeVisitor to another package, and deletes these classes from ceylon-ide-eclipse; this should happen together with another commit in ceylon-ide-common that adds these classes there (ie. they are moved from ceylon-ide-eclipse to ceylon-ide-common).

I don't know what is the current state of these classes, but if they are still in ceylon-ide-eclipse, they should be moved to common, ceylon-ide-intellij should be adapted to use the common classes (instead of their copies in ceylon-ide-intellij), and this PR abandoned.

**Comment by bjansen** [comment]
FindDeclarationNodeVisitor has already been replaced with its Ceylon implementation, but Escaping is still used in both its Java and Ceylon versions. The IntelliJ plugin already uses picks those classes in ceylon-ide-common.

I guess the simplest way is to close this PR and replace usages of `Escaping` with `escaping`.

**Comment by bjansen** [comment]
Escaping removed in https://github.com/ceylon/ceylon-ide-eclipse/commit/8a6a98b02ef221ef39cfb22b5d6cd8072f5ab164 and https://github.com/ceylon/ceylon-ide-common/commit/64551308d00a7438327d2ffb74ad9beae5435668.

**Pull request closed without merging**
